name: test

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel:
jobs:
  # This workflow contains a single job called "test":
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job:
    steps:
    # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it:
    - name: Checkout repo
      uses: actions/checkout@v2.1.0
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: '10.x'
    
    # Install dependencies including dev dependencies:
    - name: Install
      run: npm install

    # Run style test(s)
    - name: Style
      run: npx eslint src/ lib/

